version: '3.7'

networks:
  cdc-using-debezium-network:
    name: cdc-using-debezium-network
    driver: bridge

services:
  oracle-source:
    image: gvenzl/oracle-xe
    container_name: oracle-source
    hostname: oracle-source
    restart: always
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: 12345678
    volumes:
      - "oracle-source-data:/opt/oracle/oradata"
    networks:
      - cdc-using-debezium-network

  oracle-destination:
    image: gvenzl/oracle-xe:21-slim    
    container_name: oracle-destination
    hostname: oracle-destination
    restart: always
    ports:
      - "1522:1521"
    environment:
      ORACLE_PASSWORD: 12345678
    volumes:
      - "oracle-destination-data:/opt/oracle/oradata"
    networks:
      - cdc-using-debezium-network

  cdc-using-debezium-kafka:
    image: bitnami/kafka:3.4
    container_name: cdc-using-debezium-kafka
    hostname: cdc-using-debezium-kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_KRAFT_CLUSTER_ID: q0k00yjQRaqWmAAAZv955w
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: INTERNAL://cdc-using-debezium-kafka:29092,CONTROLLER://cdc-using-debezium-kafka:29093,EXTERNAL://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://cdc-using-debezium-kafka:29092,EXTERNAL://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@cdc-using-debezium-kafka:29093
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
    networks:
      - cdc-using-debezium-network

  cdc-using-debezium-connect:
    image: debezium/connect:2.3
    container_name: cdc-using-debezium-connect
    hostname: cdc-using-debezium-connect
    restart: always
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: cdc-using-debezium-kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      ENABLE_DEBEZIUM_SCRIPTING: "true"
    depends_on:
      - cdc-using-debezium-kafka
      - oracle-source
    networks:
      - cdc-using-debezium-network

  mysql-nest:
    image: mysql:8.0
    container_name: mysql-nest
    hostname: mysql-nest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: nest_db
      MYSQL_USER: nest_user
      MYSQL_PASSWORD: nest_pass
    volumes:
      - "mysql-nest-data:/var/lib/mysql"
    networks:
      - cdc-using-debezium-network

  confluent-control-center:
    image: confluentinc/cp-enterprise-control-center:7.3.1
    container_name: confluent-control-center
    hostname: confluent-control-center
    restart: always
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "cdc-using-debezium-kafka:29092"
      CONTROL_CENTER_KAFKA_CLUSTER_MODE: "KRAFT"
      CONTROL_CENTER_CONNECT_CLUSTER: "cdc-using-debezium-connect:8083"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
    depends_on:
      - cdc-using-debezium-kafka
      - cdc-using-debezium-connect
    networks:
      - cdc-using-debezium-network

volumes:
  oracle-source-data:
  oracle-destination-data:
  mysql-nest-data:
