version: '3.7'

networks:
   cdc-using-debezium-network:
       name: cdc-using-debezium-network
       driver: bridge
       external: false

services:
   cdc-using-debezium-postgres:
       image: debezium/postgres:11
       container_name: cdc-using-debezium-postgres
       hostname: cdc-using-debezium-postgres
       restart: always
       ports:
           - '5443:5432'
       environment:
           POSTGRES_PASSWORD: 123
           POSTGRES_USER: postgres
           POSTGRES_DB: cdc-using-debezium
       volumes:
           - 'cdc-using-debezium-postgres-data:/var/lib/postgresql/data'
       networks:
           - cdc-using-debezium-network

   db-mysql:
       image: mysql:8.0
       container_name: db-mysql
       hostname: db-mysql
       restart: always
       ports:
           - '3306:3306'
       environment:
           MYSQL_ROOT_PASSWORD: 12345678
           MYSQL_DATABASE: db-mysql
           MYSQL_PORT: 3306
           MYSQL_USER: my-sql
           MYSQL_PASSWORD: 'postgres' 
       volumes:
           - 'db-mysql-data:/var/lib/mysql'
       networks:
           - cdc-using-debezium-network

volumes:
   cdc-using-debezium-postgres-data:
       name: cdc-using-debezium-postgres-data
       driver: local
   db-mysql-data:
       name: db-mysql-data
       driver: local